name:                format
version:             0.1.0.0
author:              jamshid
maintainer:          j
build-type:          Simple
license:             Apache-2.0

library:
  source-dirs: src
  dependencies:
    - base
    - base16-bytestring
    - bytestring
    - template-haskell
    - text
    - time
